### ISSUE TITLE
Add message to the response body

### ISSUE THREAD

**Issue by itsalb3rt** [itsalb3rt/cloudcsv_api#11]
**Description**

We need to add the message into the response body when the email or user already exits.

https://github.com/itsalb3rt/cloudcsv_api/blob/9ac635efddfec5143b4ca13efe6ab4f20566eb6b/src/controllers/AuthController.php#L86

You can response with a json object;

```php
$this->response->setContent(json_encode(['message' => 'User Already Exist']));
```

**Comment by aanu-el** [comment]
Hi, I would like to work on this issue

**Comment by itsalb3rt** [comment]
Sure @aanu-el
